### ISSUE TITLE
Add config option to disable CURLOPT_SSL_VERIFYPEER

### ISSUE THREAD

**Issue by mstrater** [launchdarkly/c-client-sdk#27]
**Is your feature request related to a problem? Please describe.**
Our application must contain an option to disable certificate verification on network requests because certain antivirus programs that our customers use will cause verification to fail. I need a config option to disable the CURLOPT_SSL_VERIFYPEER option to address this.

**Describe the solution you'd like**
I have a working/tested change to the library to add a config option to the library. I'll make a PR as soon as I can get legal approval.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hroederld** [comment]
Hi @mstrater 

I'm not sure that totally disabling certificate verification is ideal. As I understand it anti-virus programs that MITM usually add their own root certificate to the operating systems certificate store. Because this is anti-virus I assume you are on Windows?

When you integrated the SDK into your application did you build manually build OpenSSL and link that for Curl? As far as I know OpenSSL will NOT use the operating systems certificate store by default. Windows has a built in SSL solution known as WinSSL, that DOES use the OS certificate store, as such the anti-virus should be able to safely MITM the application.

The pre-built binaries we have on our GitHub release page for this repo are built using WinSSL.

**Comment by mstrater** [comment]
To be honest, I don't know much about how anti-virus software works with respect to MITM, but we occasionally get customer reports that their anti-virus is blocking requests from our product, so we have an option for them to disable peer verification in preferences (which defaults to enabling peer verification of course), so that they can work around the issue. It has solved the issue in the past. I made https://github.com/launchdarkly/c-client-sdk/pull/28 to address the changes needed.

**Comment by hroederld** [comment]
We have a new release out with your PR addressing this issue https://github.com/launchdarkly/c-client-sdk/releases/tag/1.4.0

Thanks!

**Comment by mstrater** [comment]
Wow, thanks for the quick release, I really appreciate it!
